language: node_js

notifications:
  email: false

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

node_js:
  - "6"

script:
  - ./script/test
